---
- name: Configure New Relic deployments and alert issues
  hosts: essensys
  gather_facts: false
  roles:
    - role: sops_load
      sops_load_cloud: true
      sops_load_gateway: false
    - newrelic_alerts
    - newrelic_deployment
