---
- name: Deploy Essensys Support Site
  hosts: essensys
  become: yes

  roles:
    - common
    - database
    - backend
    - frontend
    - portal_backend
    - portal_frontend
    - portal_nginx
