---
- name: Deploy Essensys Support Site
  hosts: essensys
  become: yes

  roles:
    - common
    - database
    - backend
    - frontend
    - portal_backend
    - portal_frontend
    - portal_nginx

- name: Ensure production HTTPS after nginx deploy
  hosts: essensys
  become: yes
  import_playbook: enable-https-prod.yml
