---
- name: immudb - creer repertoire de donnees
  ansible.builtin.file:
    path: "{{ immudb_data_dir }}"
    state: directory
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: '0755'
