portal_frontend_repo: "https://github.com/essensys-hub/essensys-user-portal-frontend.git"
newrelic_browser_enabled: false
newrelic_account_id: ""
newrelic_browser_application_id: ""
newrelic_browser_agent_id: ""
newrelic_browser_trust_key: ""
