---
control_plane_image: "essensyshub/essensys-control-plane"
control_plane_version: "{{ essensys_version }}"
control_plane_name: "essensys-control-plane"
control_plane_port: 9100
control_plane_config: "{{ config_dir }}/control-plane/config.yaml"
control_plane_data: "{{ data_dir }}/control-plane"
control_plane_redis_addr: "localhost:6379"
control_plane_redis_db: 0
control_plane_log_level: "info"
control_plane_base_path: "/controle_plane"