---
- name: Arreter le Nginx systeme (migration vers Docker)
  service:
    name: nginx
    state: stopped
    enabled: false
  failed_when: false
  changed_when: false

- name: Deployer la config Nginx
  template:
    src: default.conf.j2
    dest: "{{ nginx_config_dir }}/default.conf"
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: '0644'
